version: '3'
services:
  php:
    image: php:fpm
    volumes:
      - ./code:/code
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./server_logs:/var/log/nginx
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=the_db
      - DB_USERNAME=root
      - DB_PASSWORD=TheMegaPassword
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=TheMegaPassword
      - MYSQL_DATABASE=the_db
    volumes:
      - ./db_data:/var/lib/mysql
volumes:
  db_data: